services:
  db:
    container_name: filesharing-db
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: Password@12345
      MYSQL_DATABASE: filesharing_db
      TZ: Asia/Tokyo
    ports:
      - 33093:3306
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: filesharing-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=filesharing-db
      - PMA_USER=root
      - PMA_PASSWORD=Password@12345
    depends_on:
      - db
    ports:
      - 8802:80

  app:
    container_name: filesharing-app
    build:
      context: ./app/
      dockerfile: Dockerfile
    image: filesharing/app:almalinux8-php82
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./app/etc/php.development.ini:/usr/local/etc/php/php.ini
      - ./app/php/logs:/var/log/php-fpm
      - ../filesharing:/var/www/html/filesharing
    stdin_open: true
    tty: true
    depends_on:
      - db

  nginx:
    container_name: filesharing-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../filesharing:/var/www/html/filesharing
    depends_on:
      - app

  npm:
    container_name: filesharing-npm
    image: node:18
    working_dir: /var/www/html/filesharing
    command: "bash -c 'npm install && npm run dev'"
    volumes:
      - ../filesharing:/var/www/html/filesharing
    ports:
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}

  mailhog:
    container_name: filesharing-mailhog
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
      - 1025:1025
